[package]
name = "rfs"
version = "0.1.0"
authors = ["Muhamad Azmy <muhamad.azmy@codescalers.com>"]
edition = "2018"
# build = "build.rs"
build = false

[build-dependencies]
capnpc = "0.9"

[dependencies]
fuse = "0.3"
libc = "0.2"
log = "0.4"
simple_logger = "1.0.1"
capnp = "0.9.4"