[package]
name = "rfs"
version = "0.1.0"
authors = ["Muhamad Azmy <muhamad.azmy@codescalers.com>"]
edition = "2018"
# build = "build.rs"
build = false

[build-dependencies]
capnpc = "0.9"

[dependencies]
fuse = "0.3"
libc = "0.2"
log = "0.4"
simple_logger = "1.0.1"
capnp = "0.9.4"
sqlite = "0.24.0"
blake2 = "0.8.0"
time = "0.1.42"
lru = "0.6.5"
crossbeam = "0.7.1"
redis = "0.10.0"
fs2 = "0.4.3"
snappy = "0.4.0"
xxtea = "0.2.0"
clap = "2.32.0"
num_cpus = "1.10.0"
anyhow = "1.0"
