[package]
name = "rfs"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
capnpc = "0.14.4"

[dependencies]
capnp = "0.14.3"
anyhow = "1.0.44"
time = "0.3.3"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }
tokio = { version = "1.11.0", features = ["full"] }
polyfuse = "0.4"
libc = "0.2"
futures = "0.3"
thiserror = "1.0"
redis = { version = "0.21.0", features = ["tokio-comp", "aio", "connection-manager"] }
xxtea = "0.2.0"
bytes = "1.1.0"
log = "0.4"
simple_logger = "1.0.1"
lru = "0.7.0"
nix = "0.23.0"
clap = "2.33"
tar = "0.4"
flate2 = "1.0"
daemonize = "0.4.1"
snap = "1.0.5"
assert_cmd = "2.0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[profile.release]
lto = true
codegen-units = 1
