[package]
name = "rfs"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
capnpc = "0.14.4"

[[bin]]
name = "rfs"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
build-binary = [
    "dep:polyfuse",
    "dep:simple_logger",
    "dep:tempfile",
    "dep:git-version",
    "dep:daemonize"
    ]

[lib]
name = "rfs"
path = "src/lib.rs"

[dependencies]
capnp = "0.14.3"
anyhow = "1.0.44"
time = "0.3.3"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }
tokio = { version = "1.27", features = [ "rt", "rt-multi-thread", "macros"] }
libc = "0.2"
futures = "0.3"
thiserror = "1.0"
xxtea = "0.2.0"
bytes = "1.1.0"
log = "0.4"
lru = "0.7.0"
nix = "0.23.0"
clap = "2.33"
tar = "0.4"
flate2 = "1.0"
snap = "1.0.5"
async-recursion = "1.0.0"
bb8-redis = "0.11.0"
async-trait = "0.1.53"
# next are only needed for the binarys
simple_logger = {version = "1.0.1", optional = true}
daemonize = { version = "0.5", optional = true }
git-version = { version = "0.3.5", optional = true}
tempfile = { version = "3.3.0", optional = true }

[dependencies.polyfuse]
branch = "master"
git = "https://github.com/muhamadazmy/polyfuse"
optional = true

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
assert_cmd = "2.0"

[profile.release]
lto = true
codegen-units = 1
