name: Unit and Integration Test

on:
  push:
    branches: [ test-build-github-actions ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install capnproto
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Unit Testing
      run: cargo test --bins
    - name: Config FUSE to run without sudo
      run: sudo chown -R  $USER:$USER /etc/fuse.conf && sudo echo user_allow_other >> /etc/fuse.conf
    - name: Integration Testing
      run: cargo test --release --test '*' -- --test-threads=1
