name: Unit and Integration Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: clechasseur/rs-fmt-check@v2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Unit Testing
        run: cargo test --features build-binary
        env:
          RUST_MIN_STACK: 8388608
