name: Rust

on:
  push:
    branches: [ test-build-github-actions ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install capnproto
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Unit Testing
      run: cargo test --bins
    - name: Integration Testing
      run: cargo test --release --test '*' -- --test-threads=1
      
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
